# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/Release.yml'
      - 'LICENSE'
      - 'README.md'
      - 'version-check.json'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/Release.yml'
      - 'LICENSE'
      - 'README.md'
      - 'version-check.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=version::$(awk 'NR==4' version-check.json | sed 's/"//g ; s/,//g' | awk -F": " '{print $2}')"
    - name: Set ENV for version
      env: 
        mod_version: ${{ steps.vars.outputs.version }}
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: LogisticsBridge-${{ steps.vars.outputs.version }}-${{ steps.vars.outputs.sha_short }}
        path: build/libs
