# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and release

on: 
  push:
    paths:
      - 'version-check.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Declare variable
      id: vars
      shell: bash
      run: |
        echo "::set-output name=version::$(awk 'NR==4' version-check.json | sed 's/"//g ; s/,//g' | awk -F": " '{print $2}')"

    - name: Build with Gradle
      env: 
        MOD_VER: ${{ steps.vars.outputs.version }}
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: LogisticsBridge-Artifact
        path: build/libs

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10

    - name: Create version|changelog variable
      id: vars
      run: |
        echo "::set-output name=version::$(awk 'NR==4' version-check.json | sed 's/"//g ; s/,//g' | awk -F": " '{print $2}')"
        echo "::set-output name=changelog::$(awk 'NR==8' version-check.json | sed 's/"//g ; s/,//g' | awk -F": " '{print $2}')"
        
    - name: Create GitHub Release
      uses: KorewaLidesu/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.vars.outputs.version }}
        commitish: master
        body:  ${{ steps.vars.outputs.changelog }}
        name:  ${{ steps.vars.outputs.version }}
        prerelease: false
        allow_override: true
        gzip: false
        files: |
            ./LogisticsBridge/LogisticsBridge-${{ steps.vars.outputs.version }}.jar
